### ISSUE TITLE
Azure Policy compliance

### ISSUE THREAD

**Issue by janegilring** [Azure/alz-monitor#102]
A way for customers to enable alerting for Azure Policy compliance is something I think would bring value.

[This](https://blog.tyang.org/2021/12/06/monitoring-azure-policy-compliance-states-2021-edition/) article have a nice overview of possible ways to approach this.

Regardless of approach, getting the data into Log Analytics to be able to leverage Azure Monitor Alerts would be the most optimal in my opinion.

**Comment by paulgrimley** [comment]
@janegilring we have discussed this and are looking at a workbook to present these @scautomation is defining a spec for this dashboard if you wanted to input. If others feel alerts are required would welcome adding to this thread. cc: @jfaurskov

**Comment by janegilring** [comment]
Now that we can [Query Azure Resource Graph from Azure Monitor](https://techcommunity.microsoft.com/t5/azure-observability-blog/query-azure-resource-graph-from-azure-monitor/ba-p/3918298), monitoring and alerting for Azure Policy compliance is becoming easier.
The [documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/azure-monitor-data-explorer-proxy) has also been updated.
There is also an excellent walkthrough in [this article](https://blog.tyang.org/2023/09/30/natively0monitoring-azure-policy-compliance-states-in-azure-monitor-2023-edition/) on how to leverage this new capability.

**Comment by paulgrimley** [comment]
@janegilring we discussed this the other day and alerts for policy compliance would likely overwhelm the policy engine and a better approach is a dashboard as mentioned above. We're looking at this from an all up ALZ rather than AMBA so we can have broader coverage. We're also moving to aka.ms/amba as you are likely aware so please add any new issues in the new location, thanks!
