### ISSUE TITLE
Question:Policy default effect - disabled

### ISSUE THREAD

**Issue by gerrynicol** [Azure/alz-monitor#236]
Hi there,

Please could you provide a bit more information on why some of the policy's in the initiaitives have the 'disabled' policy effect. I may have missed the reasoning behind this.

Thanks

**Comment by arjenhuitema** [comment]
Hi @gerrynicol, thank you for highlighting this. I realise that we don´t have documentation explaining the reasoning for a alert to be disabled by default.

The disabled policies are included because they may be of specific interest to some customers. In general, we evaluate the alert rules on best practices, field experience, customer feedback, type of alert and possible impact. There are situations where disabling the policy by default makes sense to prevent receiving unnecessary and/ or duplicate alerts/ notifications. For example we deploy an alert rule for VPN Gateway Bandwidth Utilization, in turn we have disabled the alert rules for VPN Gateway Egress and Ingress. 

The default is intended to provide a well balanced baseline. Everything is parameterized, and flexible, we encourage you to make any modifications to the alerts that are of interest to you.

Thanks.

**Comment by paulgrimley** [comment]
@gerrynicol closing as addressed as before please raise on new repo if still an issue
