### ISSUE TITLE
Several broken links in wiki

### ISSUE THREAD

**Issue by jeremiahhoward** [Azure/alz-monitor#238]
Many of the links ./filename.md reference ./filename (without file extension).

**Comment by arjenhuitema** [comment]
Hello @jeremiahhoward,

Thank you for raising this issue. I´ve reviewed the PR and have the following observations:

**One of the changes in the PR you proposed is adding /docs/:** 
Current `[Alert Details](https://github.com/Azure/alz-monitor/wiki/AlertsDetails)`
New `[Alert Details](https://github.com/Azure/alz-monitor/docs/wiki/AlertsDetails.md)`

Making this change, will render a page not found error. 

![image](https://github.com/Azure/alz-monitor/assets/15944031/0e672c1b-ef8e-4d58-a392-bf303b8feaa6)

While we organize and edit the documentation for the wiki in the docs folder, the wiki in GitHub itself is a separate repo. We use a workflow to synchronize the content between the docs/wiki and the wiki repo. The links in the docs are configured to work for reading the wiki version of the documents. 

![image](https://github.com/Azure/alz-monitor/assets/15944031/b7c22a1c-bf4f-46a3-bc96-a2561bfe2312)

**Adding the extension ".md" will break the formatting** 
For example, calling AlertsDetails.md will render the raw file:

![image](https://github.com/Azure/alz-monitor/assets/15944031/ab4eb714-116a-4690-8062-c71eed6f32b8)

Concluding, the links in the wiki are configured correctly. As it is our intention that the wiki is used, rather than browsing the documentation from the code view.

Please let us know if there are other questions/ concerns.

I will proceed to close the PR and this Issue. 

Thank you.
